const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  TOGGLE_MENU: "TOGGLE_MENU",
  ADD_ITEM: "ADD_ITEM",
  FETCH_CART_ITEMS: "FETCH_CART_ITEMS",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART"
};

export default CartActionTypes;
